# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aurl < Formula
  desc ""
  homepage ""
  version "1.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/classmethod/aurl/releases/download/1.1.6/aurl_1.1.6_Darwin_x86_64.tar.gz"
      sha256 "9779b3a9567eea5248363b950b05a70cf7bd79ee758ee7ce7c734a2c6acb8610"

      def install
        bin.install "aurl"
        # bash_completion.install "completions/aurl.bash" => "aurl"
        # ...
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/classmethod/aurl/releases/download/1.1.6/aurl_1.1.6_Darwin_arm64.tar.gz"
      sha256 "abb5072789753ce6467f74760732a4c6dedb93d929eb9195055ef4b17833383d"

      def install
        bin.install "aurl"
        # bash_completion.install "completions/aurl.bash" => "aurl"
        # ...
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/classmethod/aurl/releases/download/1.1.6/aurl_1.1.6_Linux_arm64.tar.gz"
      sha256 "4ca8f6397987b5f3e089f9c99fefa4f9ba6e845e7a9dd64845f16210f10b66b3"

      def install
        bin.install "aurl"
        # bash_completion.install "completions/aurl.bash" => "aurl"
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/classmethod/aurl/releases/download/1.1.6/aurl_1.1.6_Linux_x86_64.tar.gz"
      sha256 "d543770edf9fd0b219e00dfadba35ee562bdd2447815a2b2731c07f1303d5ce9"

      def install
        bin.install "aurl"
        # bash_completion.install "completions/aurl.bash" => "aurl"
        # ...
      end
    end
  end

  test do
    system "#{bin}/aurl --version"
    # ...
  end
end
