# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aurl < Formula
  desc ""
  homepage ""
  version "1.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/classmethod/aurl/releases/download/1.1.1/aurl_1.1.1_Darwin_arm64.tar.gz"
      sha256 "f714cbd54d5394ce68ce8c9eea449268bb1968b1c080ed857f43787675fe10b4"

      def install
        bin.install "some_other_name"
        # bash_completion.install "completions/aurl.bash" => "aurl"
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/classmethod/aurl/releases/download/1.1.1/aurl_1.1.1_Darwin_x86_64.tar.gz"
      sha256 "ec75fad5a6311d95c386a031362a378571ffec2c2204667fcfeb5f102544898c"

      def install
        bin.install "some_other_name"
        # bash_completion.install "completions/aurl.bash" => "aurl"
        # ...
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/classmethod/aurl/releases/download/1.1.1/aurl_1.1.1_Linux_arm64.tar.gz"
      sha256 "f8f9b07fae46b8368bdc3f239be5bb196928db146d490bf5dd4f734a9f1390de"

      def install
        bin.install "some_other_name"
        # bash_completion.install "completions/aurl.bash" => "aurl"
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/classmethod/aurl/releases/download/1.1.1/aurl_1.1.1_Linux_x86_64.tar.gz"
      sha256 "0c4dc3d80a4d56736a37d1c4321d590f6a0435a6883dee1ee33e58ff6e5113e5"

      def install
        bin.install "some_other_name"
        # bash_completion.install "completions/aurl.bash" => "aurl"
        # ...
      end
    end
  end

  test do
    system "#{bin}/aurl --version"
    # ...
  end
end
