# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aurl < Formula
  desc ""
  homepage ""
  version "1.1.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/classmethod/aurl/releases/download/1.1.5/aurl_1.1.5_Darwin_arm64.tar.gz"
      sha256 "95eb6166ad64fb1751bf792335ffeeba7a4e9589a0af2ac18877d14ccd85cdf8"

      def install
        bin.install "aurl"
        # bash_completion.install "completions/aurl.bash" => "aurl"
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/classmethod/aurl/releases/download/1.1.5/aurl_1.1.5_Darwin_x86_64.tar.gz"
      sha256 "01fb825c3a9cfc6397e6ec8749325320568074413e0043103c850761ff79f1e1"

      def install
        bin.install "aurl"
        # bash_completion.install "completions/aurl.bash" => "aurl"
        # ...
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/classmethod/aurl/releases/download/1.1.5/aurl_1.1.5_Linux_arm64.tar.gz"
      sha256 "1a8fab6bed86d4df322799bd86925591ecafbe3d26c61005b7a8a49ae26c7455"

      def install
        bin.install "aurl"
        # bash_completion.install "completions/aurl.bash" => "aurl"
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/classmethod/aurl/releases/download/1.1.5/aurl_1.1.5_Linux_x86_64.tar.gz"
      sha256 "6587a2a8f1639a00d9222652848f82630af27e363d4628a63bf680d206e228ac"

      def install
        bin.install "aurl"
        # bash_completion.install "completions/aurl.bash" => "aurl"
        # ...
      end
    end
  end

  test do
    system "#{bin}/aurl --version"
    # ...
  end
end
